# MARK: - WAS Runtime Secret Provider

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: greentech-db
  namespace: greentech
spec:
  provider: gke

  parameters:
    secrets: |
      # MARK: - Cloud SQL
      - resourceName: "projects/ncp-gcp-dr-v2/secrets/greentech-db-url/versions/1"
        path: "DB_URL"
      - resourceName: "projects/ncp-gcp-dr-v2/secrets/greentech-db-username/versions/1"
        path: "DB_USERNAME"
      - resourceName: "projects/ncp-gcp-dr-v2/secrets/greentech-db-password/versions/1"
        path: "DB_PASSWORD"

      # MARK: - Application Runtime
      - resourceName: "projects/ncp-gcp-dr-v2/secrets/greentech-jwt-secret/versions/1"
        path: "JWT_SECRET"
      - resourceName: "projects/ncp-gcp-dr-v2/secrets/greentech-field-encryption-key/versions/1"
        path: "FIELD_ENCRYPTION_KEY"
      - resourceName: "projects/ncp-gcp-dr-v2/secrets/greentech-admin-username/versions/1"
        path: "ADMIN_USERNAME"
      - resourceName: "projects/ncp-gcp-dr-v2/secrets/greentech-admin-password/versions/1"
        path: "ADMIN_PASSWORD"

      # MARK: - NCP Object Storage
      - resourceName: "projects/ncp-gcp-dr-v2/secrets/greentech-storage-access-key/versions/1"
        path: "NCP_STORAGE_ACCESS_KEY"
      - resourceName: "projects/ncp-gcp-dr-v2/secrets/greentech-storage-secret-key/versions/1"
        path: "NCP_STORAGE_SECRET_KEY"