# MARK: - WAS ServiceAccount

apiVersion: v1
kind: ServiceAccount
metadata:
  name: greentech-was
  namespace: greentech
  annotations:
    iam.gke.io/gcp-service-account: dr-rebuild-lab-was@ncp-gcp-dr-v2.iam.gserviceaccount.com
    iam.gke.io/return-principal-id-as-email: "true"